name: Verify

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up mise
        uses: jdx/mise-action@v2
      - name: Verify
        run: mise run verify
